### ISSUE TITLE
Add Insert or Update

### ISSUE THREAD

**Issue by confile** [ticketbis/grails-groobalize#17]
You created: 

```
def book = new Book(author: "Endika", releaseDate: new Date())

book.addToTranslations(title: "english title", synopsis: "synopsis in english", locale: new Locale('en'))
```

In case the translation does exist it creates a new one with the same language code. This does not make any sense. Could you please change that if a translation with the same Locale does exist it updates the translation.

**Comment by endikag** [comment]
There are no constraints on duplicated locales for same source by default (intentionally); In case you need to make this unique you should add `locale(unique: 'source')` to `constraints` on Translation class.
Then you can use `Translation.findOrCreateBySourceAndLocale(source, locale)` to retrieve or create translation.
