### ISSUE TITLE
WithFallbackLocaleContext misleading

### ISSUE THREAD

**Issue by confile** [ticketbis/grails-groobalize#19]
I cannot set the locale like this: 

```
LCH.locale = new Locale("en")
```

and set the fallback like this: 

```
LCH.localeContext = new WithFallbackLocaleContext([new Locale('de')])
```

This will not set the locale to en and the fallback to de it just sets the locale to de with no fallback.

**Comment by endikag** [comment]
You can set `locale` or `localeContext` but no both.

```
LCH.localeContext = new WithFallbackLocaleContext([Locale.ENGLISH, Locale.GERMAN]) // 'en' is the default locale
```

**Comment by confile** [comment]
Could you add this to the docu please.

**Comment by endikag** [comment]
`LocaleContextHolder` is part of Spring. You can see it's documentation [here](https://docs.spring.io/spring/docs/current/javadoc-api/org/springframework/context/i18n/LocaleContextHolder.html)
