### ISSUE TITLE
Working with Database Migration

### ISSUE THREAD

**Issue by confile** [ticketbis/grails-groobalize#5]
Could you please explain how to use this plugin with database migration. How are new languate fields added?

**Comment by endikag** [comment]
The only fields added are `source` and `locale` to the translation table as you can see [here](https://github.com/ticketbis/grails-groobalize/blob/master/src/groovy/com/ticketbis/groobalize/Translation.groovy).
Grails will automatically generate the columns for those fields.

**Comment by confile** [comment]
Thanks
