### ISSUE TITLE
Using in a Service

### ISSUE THREAD

**Issue by confile** [ticketbis/grails-groobalize#6]
Could you please explain how to use this plugin in a service. There is no locale from a request like in a Controller. How do I define the locale to choose from?

**Comment by endikag** [comment]
It uses spring's LocaleContextHolder (http://docs.spring.io/spring/docs/current/javadoc-api/org/springframework/context/i18n/LocaleContextHolder.html) that acts like a global variable in the request.

**Comment by confile** [comment]
@endSly Could you please give a short example how you would use this plugin in a service? 

I also use the Grails jaxrs plugin. Incoming REST request do not have the spring security locale being set. Although I know the Locale from a request parameter how do I attach this locale to this plugin to work with the right i18n?

Thanks for help. I think you plugin is really a missing peace in the grails plugin world.
