### ISSUE TITLE
String synopsis = null // Inherit from parent locale

### ISSUE THREAD

**Issue by steffimueller** [ticketbis/grails-groobalize#7]
In your example: 

```
class BookTranslation extends Translation<Book> {
    @Field(inherit=false)
    String title

    String synopsis = null // Inherit from parent locale

    static constraints = {
        synopsis(nullable: true)
    }
}
```

What does the following means?

> Inherit from parent locale

I have a class: 

```
class Car {
   String name
}

class SpecialCar extends Car {
   String type
}
```

How do I make the translation for type and name?

**Comment by jonan** [comment]
If you ask for a translation that's not available the plug-in will try to get you the parent locale.

For example, if you ask for the locale `en_US` and there's no translation for it, you will get the `en` text. But if you add the annotation `@Field(inherit=false)` to a field you'll get `null`, as that field will never try to get a different locale.

This two files should give you an idea of how to translate your classes: [Book.groovy](https://github.com/ticketbis/grails-groobalize/blob/master/test/projects/demo/grails-app/domain/demo/Book.groovy) and [BookTranslation.groovy](https://github.com/ticketbis/grails-groobalize/blob/master/test/projects/demo/grails-app/domain/demo/BookTranslation.groovy)

**Comment by steffimueller** [comment]
1. I still do not get what is the parent locale? Does this mean inherit from default locale which is en in your example?
2. How do I set the default locale? Do I have to set it for each individually? 
3. What if default locale is en, en in empty. Assume that locale de is filled. When a user requests locale fr which happens then will he get de because this is the only filled locale or will he get empty en?
