### ISSUE TITLE
Does not work with Database-migration plugin

### ISSUE THREAD

**Issue by MartinBusch** [ticketbis/grails-groobalize#8]
This plugin does not work with the database migration plugin (1.4.0)

**Comment by confile** [comment]
@jonan Do you have a solution on this?

**Comment by steffimueller** [comment]
A little help would be great. @jonan

**Comment by jonan** [comment]
Sorry, we have no solution yet.

**Comment by confile** [comment]
Well, how can you work with it if it does not work with database migration?

**Comment by MartinBusch** [comment]
@jonan Could you please support database migration otherwise I will not be able to use this library which is awesome.

**Comment by steffimueller** [comment]
+1 that would be great. I also cannot use it without migration.

**Comment by confile** [comment]
+1 me too

**Comment by jonan** [comment]
We don't use _database-migrations_ so this is not a priority for us ATM, sorry.

**Comment by confile** [comment]
Could you please give any hint how this could work? If I can I will work on it but I have no idea what to do.

**Comment by endikag** [comment]
We've added this issue to [known issues](https://github.com/ticketbis/grails-groobalize#known-issues), but, for now, we won't spend time trying to fix it.
Please, feel free to pull request if you can find the fix for that issue.

**Comment by confile** [comment]
@endSly Could you please give any hint what I can do?

**Comment by endikag** [comment]
I think it could be due to AST transformations being applied after the database-migration plugin inspects the classes.

**Comment by confile** [comment]
I am not familiar with AST but could you apply this before db migration takes place? This would solve all the problems.

**Comment by confile** [comment]
@endSly I will try to make this work with Database Migration. Could you please give me a hint on what to do?
